{% set name = "opentelemetry-semantic-conventions-ai" %}
{% set version = "0.4.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 94efa9fb4ffac18c45f54a3a338ffeb7eedb7e1bb4d147786e77202e159f0036

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - poetry-core
    - pip
  run:
    - python

test:
  imports:
    - opentelemetry.semconv_ai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Semantic Conventions Extension for Large Language Models
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    This is an extension of the standard OpenTelemetry Semantic Conventions for gen AI applications. 
    It defines additional attributes for spans that are useful for debugging and monitoring prompts, completions, token usage, etc.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
